export const SocketMessageTypes = {
    CONNECTED_CLIENT: 'CONNECTED_CLIENT',
    CLIENT_REGISTRATION: 'CLIENT_REGISTRATION',
    ROOMS_REQUEST: 'ROOMS_REQUEST',
    ROOMS_RESPONSE: 'ROOMS_RESPONSE',
};
